name = "auth"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_CONVEX_URL = "https://academic-mandrill-512.convex.cloud"
PUBLIC_CONVEX_SITE_URL = "https://academic-mandrill-512.convex.site"
