import { ConvexClientProvider } from './ConvexClientProvider';

import type { Metadata } from 'next';
import './globals.css';

// Primitives
import { Toaster } from '@/components/primitives/ui/sonner';
// Components
import OrganizationSwitcher from '@/components/organizations/ui/OrganizationSwitcher';
import UserButton from '@/components/users/ui/UserButton';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="authapp">
			<body className={`grid h-screen grid-rows-[auto_1fr] antialiased`}>
				<ConvexClientProvider>
					<div className="flex items-center justify-between gap-5 p-4">
						<div className="mr-auto text-2xl font-bold text-white">Next.js</div>
						<OrganizationSwitcher />
						<UserButton />
					</div>
					{children}
				</ConvexClientProvider>
				<Toaster position="top-center" />
			</body>
		</html>
	);
}
